const pokemons = [
  "Bulbasaur", "Ivysaur", "Venusaur",
  "Charmander", "Charmeleon", "Charizard",
  "Squirtle", "Wartortle", "Blastoise",
  "Caterpie", "Metapod", "Butterfree",
  "Weedle", "Kakuna", "Beedrill",
  "Pidgey", "Pidgeotto", "Pidgeot",
  "Rattata", "Raticate",
  "Spearow", "Fearow",
  "Ekans", "Arbok",
  "Pikachu", "Raichu",
  "Sandshrew", "Sandslash",
  "Nidoran♀", "Nidorina", "Nidoqueen",
  "Nidoran♂", "Nidorino", "Nidoking",
  "Clefairy", "Clefable",
  "Vulpix", "Ninetales",
  "Jigglypuff", "Wigglytuff",
  "Zubat", "Golbat",
  "Oddish", "Gloom", "Vileplume",
  "Paras", "Parasect",
  "Venonat", "Venomoth",
  "Diglett", "Dugtrio",
  "Meowth", "Persian",
  "Psyduck", "Golduck",
  "Mankey", "Primeape",
  "Growlithe", "Arcanine",
  "Poliwag", "Poliwhirl", "Poliwrath",
  "Abra", "Kadabra", "Alakazam",
  "Machop", "Machoke", "Machamp",
  "Bellsprout", "Weepinbell", "Victreebel",
  "Tentacool", "Tentacruel",
  "Geodude", "Graveler", "Golem",
  "Ponyta", "Rapidash",
  "Slowpoke", "Slowbro",
  "Magnemite", "Magneton",
  "Farfetch’d",
  "Doduo", "Dodrio",
  "Seel", "Dewgong",
  "Grimer", "Muk",
  "Shellder", "Cloyster",
  "Gastly", "Haunter", "Gengar",
  "Onix",
  "Drowzee", "Hypno",
  "Krabby", "Kingler",
  "Voltorb", "Electrode",
  "Exeggcute", "Exeggutor",
  "Cubone", "Marowak",
  "Hitmonlee", "Hitmonchan",
  "Lickitung",
  "Koffing", "Weezing",
  "Rhyhorn", "Rhydon",
  "Chansey",
  "Tangela",
  "Kangaskhan",
  "Horsea", "Seadra",
  "Goldeen", "Seaking",
  "Staryu", "Starmie",
  "Mr. Mime",
  "Scyther",
  "Jynx",
  "Electabuzz",
  "Magmar",
  "Pinsir",
  "Tauros",
  "Magikarp", "Gyarados",
  "Lapras",
  "Ditto",
  "Eevee", "Vaporeon", "Jolteon", "Flareon",
  "Porygon",
  "Omanyte", "Omastar",
  "Kabuto", "Kabutops",
  "Aerodactyl",
  "Snorlax",
  "Articuno", "Zapdos", "Moltres",
  "Dratini", "Dragonair", "Dragonite",
  "Mewtwo"
];
 

const pokemonImages = [
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/001.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/002.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/003.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/004.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/005.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/006.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/007.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/008.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/009.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/010.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/011.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/012.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/013.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/014.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/015.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/016.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/017.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/018.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/019.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/020.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/021.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/022.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/023.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/024.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/025.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/026.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/027.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/028.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/029.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/030.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/031.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/032.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/033.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/034.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/035.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/036.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/037.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/038.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/039.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/040.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/041.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/042.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/043.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/044.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/045.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/046.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/047.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/048.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/049.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/050.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/051.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/052.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/053.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/054.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/055.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/056.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/057.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/058.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/059.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/060.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/061.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/062.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/063.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/064.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/065.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/066.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/067.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/068.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/069.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/070.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/071.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/072.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/073.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/074.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/075.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/076.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/077.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/078.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/079.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/080.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/081.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/082.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/083.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/084.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/085.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/086.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/087.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/088.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/089.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/090.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/091.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/092.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/093.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/094.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/095.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/096.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/097.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/098.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/099.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/100.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/101.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/102.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/103.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/104.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/105.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/106.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/107.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/108.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/109.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/110.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/111.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/112.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/113.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/114.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/115.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/116.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/117.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/118.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/119.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/120.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/121.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/122.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/123.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/124.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/125.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/126.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/127.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/128.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/129.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/130.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/131.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/132.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/133.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/134.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/135.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/136.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/137.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/138.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/139.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/140.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/141.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/142.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/143.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/144.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/145.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/146.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/147.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/148.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/149.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/150.png"
];


function fnListarPokemon(){
    let i = fnRolarDados()
    document.getElementById("numero").innerHTML = `#${i+1}`
    document.getElementById("nome").innerHTML = pokemons [i]
    document.getElementById("foto").src = pokemonImages[i]
}

function fnRolarDados(){
    let min = 0
    let max = 149
    let numeroSorteado = Math.floor(Math.random() * (max-min+ 1)) + min

    return numeroSorteado
}

fnListarPokemon()